обслуживание:
  status: active
  equipments:
    - шестигранники
    - torx
    - насос
    - смазка цепи

везти ремкоплект:
  status: active
  equipments:
    - сумка для ремкомплекта

прокол:
  status: active
  equipments:
    - запасные камеры
    - ремкомплект для камеры
    - монтажки

порыв цепи:
  status: active
  equipments:
    - замок цепи на 10
    - замок цепи на 11
    - замок цепи на 9
    - выжимка цепи

порыв покрышки:
  status: active
  equipments:
    - ремкомплект для покрышки
    - запасная покрышка 26
    - запасная покрышка 29
    - запасная покрышка 27

порыв гидролинии тормоза:
  status: active
  equipments:
    - задний тормоз полностью готовый
    - шестигранники

Порыв тросика тормоза:
  status: active
  equipments:
    - тросик тормоза
    - шестигранники
    - концевик на тросик
    - плоскогубцы с кусачками

порыв тросика переключения:
  status: active
  equipments:
    - тросик переключения
    - шeстигранники
    - концевик на тросик
    - плоскогубцы с кусачками
    - отвертка крестовая
    - отвертка плоская

тормоза стерлись:
  status: active
  equipments:
    - тормозные колодки

тормоза регулировка:
  status: active
  equipments:
    - плоскогубцы
    - шестигранники

сломалась стойка багажника:
  status: active
  equipments:
    - ремкомплект для стойки багажника

лопнула спица:
  status: active
  equipments:
    - спицы
    - спицевой ключ

регулировка переключателей:
  status: active
  equipments:
    - шестигранники
    - отвертка крестовая
    - отвертка плоская
    - плоскогубцы

сломалась задняя ось:
  status: active
  equipments:
    - ось 135*9

разборка великов:
  status: active
  equipments:
    - педальный ключ
    - шестигранники

заклинило рулевую:
  status: inactive

заклинило каретку:
  status: inactive

сломалась передняя ось:
  status: inactive

стравило вилку:
  status: inactive

срезало болт багажника:
  status: active
  equipments:
    - запасные болты багажника

сломалась педаль:
  status: active
  equipments:
    - запасные педали